field: 60048af4-ec20-4feb-b4a7-8acfbabe0683
fieldLayouts:
  f56f471d-951c-4347-8f19-4bbf1bb53421:
    tabs:
      -
        fields:
          2e75faa6-d16d-43cc-8990-a6bc6d131cc5:
            required: false
            sortOrder: 3
          6c558a71-8a0a-48fa-8cd5-d6a5236b308c:
            required: false
            sortOrder: 2
          b21ad416-eb07-401c-84cf-20347c5801f5:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  2e75faa6-d16d-43cc-8990-a6bc6d131cc5:
    contentColumnType: text
    fieldGroup: null
    handle: lockupSubhead
    instructions: ''
    name: 'Lockup Subhead'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Links.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  6c558a71-8a0a-48fa-8cd5-d6a5236b308c:
    contentColumnType: text
    fieldGroup: null
    handle: lockupHeader
    instructions: ''
    name: 'Lockup Header'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Links.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b21ad416-eb07-401c-84cf-20347c5801f5:
    contentColumnType: text
    fieldGroup: null
    handle: embedLink
    instructions: 'Add the Vimeo video ID here'
    name: 'Vimeo Video ID'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: '336812660'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: vimeoVideoLockup
name: 'Vimeo Video Lockup'
sortOrder: 5
