fieldLayouts:
  6edc0daf-61c8-4fa1-9816-063b1a41c278:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: d499c44e-e0d4-47e4-a4ec-d2f7727d723f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1415759b-6389-4def-bb9e-8b9ec049419d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: '404'
        sortOrder: 1
handle: fourOhFourPage
hasTitleField: false
name: '404 Page'
section: b94bc776-14fa-47f3-9e27-070ac0ed1e2d # 404 Page
sortOrder: 1
titleFormat: '{section.name|raw}'
