fieldLayouts:
  4f0a0c9b-c95b-4692-af88-f24776f0607f:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 5f150873-f54d-43d9-847e-61f60318b76c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4b96664e-b12f-47fe-9f83-8eafd29af83c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ddf571c5-79db-4ffa-a333-336ad99b21fc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5e84d008-2762-4327-b794-72545f962ae3
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: getHelp
hasTitleField: false
name: 'Get Help'
section: 9c7b29fe-1f45-447b-8969-10c74e436307 # Get Help
sortOrder: 1
titleFormat: '{section.name|raw}'
