fieldLayouts:
  a13b7500-ad4b-4412-bada-a8700cc21b6c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 5f150873-f54d-43d9-847e-61f60318b76c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4b96664e-b12f-47fe-9f83-8eafd29af83c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ddf571c5-79db-4ffa-a333-336ad99b21fc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5e84d008-2762-4327-b794-72545f962ae3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0351adb2-cdbf-42e3-b0e4-53c558df4335
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Common
        sortOrder: 1
handle: styleGuide
hasTitleField: false
name: 'Style Guide'
section: a363bf5b-8a6d-4460-a231-cbb64cd56d98 # Style Guide
sortOrder: 1
titleFormat: '{section.name|raw}'
