contentColumnType: string
fieldGroup: 43a12f84-7764-4426-8c01-a05e8c6055c5
handle: imageField
instructions: ''
name: 'Image Field'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:38402d41-2ff3-4e10-8f75-6cbc1edb2981'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:38402d41-2ff3-4e10-8f75-6cbc1edb2981'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:38402d41-2ff3-4e10-8f75-6cbc1edb2981'
  targetSiteId: null
  useSingleFolder: ''
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
