enableVersioning: true
handle: styleGuide
name: 'Style Guide'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  35707b9d-7d83-4c03-a9d7-ac32c06e1ccb:
    enabledByDefault: true
    hasUrls: true
    template: views/_entry
    uriFormat: style-guide
type: single
